### PR TITLE
Support for cc and bcc

### PR DESCRIPTION
**Pull request by VILLAN3LL3**
Sorry, the .net8 changes are also included here because I have already merged them into my master branch. Feel free to cherry pick the commits which are relevant for the cc and bcc feature

### CODE REVIEW

**Comment by cmendible** [comment]
@VILLAN3LL3 can you please rebase this PR with latest `master`

**Comment by VILLAN3LL3** [comment]
@cmendible Is something still missing or can the PR be merged?

**Comment by cmendible** [comment]
> @cmendible Is something still missing or can the PR be merged?

Just need to know were is the `EmailAddressComparer` class used.

**Comment by VILLAN3LL3** [comment]
How are things @cmendible ?

**Comment by cmendible** [comment]
Great thanks and you? I'm waiting for your answer on were is the EmailAddressComparer class used.

**Comment by VILLAN3LL3** [comment]
> Great thanks and you? I'm waiting for your answer on were is the EmailAddressComparer class used.

I have already answered your question long time ago, but now I recognized that the comment was still in pending state :-/ I hope you can see it now?

**Comment by VILLAN3LL3** [comment]
@cmendible The EmailComparer is used in netDumbster/SmtpMessage.cs

**Review by cmendible — APPROVED** [review]
LGTM

**Pull request merged**
